trigger:
  branches:
    include:
    - master
    - story/perf/*
    exclude:
    - develop

pool: ubuntu-latest

steps:
- bash: |
  displayName: Read branch name
- bash: |
  displayName: Create reproducible test archive
- bash: |
  displayName: Publish test to build
- bash: |
  Run CI test {{testName}} from archive
- bash: |
  Run Regression CI test
