trigger:
  branches:
    include:
    - master
    - story/perf/*
    exclude:
    - develop

pool: 
  vmImage: ubuntu-latest

steps:
- bash: |

  displayName: Read branch name

- bash: |

  displayName: Create reproducible test archive

- bash: |

  displayName: Publish test to build

- bash: |
  
  displayName: Run CI test {{testName}} from archive

- bash: |
  
  displayName: Run Regression CI test
