trigger:
  branches:
    include:
    - master
    - story/perf/*
    exclude:
    - develop

pool: 
  vmImage: ubuntu-latest

steps:
- bash: |
    echo "We will us '$(Build.SourceBranchName)' as k6 exec name"
    echo "##vso[task.setvariable variable=k6exec]$(Build.SourceBranchName)" #alias really
  displayName: Set k6 exec function

- task: k6-load-test@0
  inputs:
    filename: k6_ci_runner.js
    args: -e mode=ci -e exec=$(k6exec)

  displayName: Create reproducible test archive

- bash: |

  displayName: Publish test to build

- bash: |
  
  displayName: Run CI test {{testName}} from archive

- bash: |
  
  displayName: Run Regression CI test
